import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import { NetworkDevice, NetworkInfo, SecurityAuditResult } from '@/types';

interface ExportData {
  networkInfo: NetworkInfo;
  devices: NetworkDevice[];
  auditResult?: SecurityAuditResult;
  timestamp: Date;
}

function formatTXT(data: ExportData): string {
  const lines: string[] = [
    '=== NetScope Network Report ===',
    `Generated: ${data.timestamp.toLocaleString()}`,
    '',
    '--- Network Info ---',
    `SSID: ${data.networkInfo.ssid}`,
    `Local IP: ${data.networkInfo.localIP}`,
    `Public IP: ${data.networkInfo.publicIP}`,
    `Gateway: ${data.networkInfo.gateway}`,
    `ISP: ${data.networkInfo.isp}`,
    `Location: ${data.networkInfo.city}, ${data.networkInfo.country}`,
    '',
    `--- Devices (${data.devices.length}) ---`,
  ];

  data.devices.forEach((d, i) => {
    lines.push(`${i + 1}. ${d.hostname} (${d.ip}) — ${d.vendor} — ${d.trust}`);
  });

  if (data.auditResult) {
    lines.push('', `--- Security Score: ${data.auditResult.score}/100 (${data.auditResult.grade}) ---`);
    data.auditResult.findings.forEach(f => {
      lines.push(`• [${f.severity.toUpperCase()}] ${f.title}: ${f.description}`);
    });
  }

  lines.push('', '--- Generated by NetScope ---');
  lines.push('https://github.com/mkr-infinity/NetScope');
  return lines.join('\n');
}

export async function exportData(
  data: ExportData,
  format: 'txt' | 'json',
): Promise<boolean> {
  if (Platform.OS === 'web') return false;
  try {
    const content = format === 'json' ? JSON.stringify(data, null, 2) : formatTXT(data);
    const ext = format === 'json' ? 'json' : 'txt';
    const filename = `netscope-report-${Date.now()}.${ext}`;
    const path = `${FileSystem.cacheDirectory}${filename}`;
    await FileSystem.writeAsStringAsync(path, content, { encoding: FileSystem.EncodingType.UTF8 });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(path, { mimeType: format === 'json' ? 'application/json' : 'text/plain' });
      return true;
    }
    return false;
  } catch {
    return false;
  }
}
