export interface EducationEntry {
  title: string;
  what: string;
  how: string;
  why: string;
  tip: string;
}

export const EDUCATION: Record<string, EducationEntry> = {
  rssi: {
    title: 'Signal Strength (RSSI)',
    what: 'RSSI (Received Signal Strength Indicator) measures how strong the WiFi signal is at your device.',
    how: 'Measured in dBm (decibel-milliwatts). A higher absolute number means weaker signal — -40 dBm is excellent, -80 dBm is poor.',
    why: 'Weak signal causes slow speeds, dropped connections, and high latency. It\'s affected by distance and obstacles.',
    tip: 'Keep your device within 10 meters of your router for best results. Walls and appliances reduce signal significantly.',
  },
  latency: {
    title: 'Latency (Ping)',
    what: 'Latency is the time it takes for data to travel from your device to a server and back.',
    how: 'Measured in milliseconds (ms). Lower is better. It\'s calculated by sending a small packet and timing the round trip.',
    why: 'High latency makes games lag, video calls stutter, and web pages load slowly.',
    tip: 'Under 20ms is excellent. 20-80ms is good. Over 150ms will cause noticeable issues in real-time applications.',
  },
  jitter: {
    title: 'Jitter',
    what: 'Jitter is the variation in latency over time — how inconsistent your ping is.',
    how: 'Calculated as the difference between the highest and lowest ping in a series of measurements.',
    why: 'High jitter causes choppy video calls and unstable gaming even if average latency is low.',
    tip: 'Jitter under 10ms is ideal. Over 30ms will noticeably impact VoIP and video calls.',
  },
  packet_loss: {
    title: 'Packet Loss',
    what: 'Packet loss occurs when data packets traveling across the network fail to reach their destination.',
    how: 'Measured as a percentage of sent packets that never arrive. Even 1-2% loss causes serious performance issues.',
    why: 'Packet loss causes re-transmissions which slow down connections significantly and cause audio/video dropouts.',
    tip: '0% is ideal. Any consistent packet loss indicates a network problem that needs investigation.',
  },
  dns: {
    title: 'DNS (Domain Name System)',
    what: 'DNS translates human-readable domain names (google.com) into IP addresses (142.250.80.46) that computers use.',
    how: 'When you visit a website, your device asks a DNS server for the IP address first, then connects to it.',
    why: 'Slow or unreliable DNS causes websites to load slowly even if your internet connection is fast.',
    tip: 'Try using 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google) instead of your ISP\'s DNS for faster, more private lookups.',
  },
  gateway: {
    title: 'Gateway (Router)',
    what: 'Your gateway is the device (usually your router) that connects your local network to the internet.',
    how: 'It\'s typically the first IP on your subnet — if your IP is 192.168.1.x, your gateway is likely 192.168.1.1.',
    why: 'All your internet traffic flows through the gateway. Its health directly impacts your entire network.',
    tip: 'Can\'t reach your gateway? Your router may have crashed. Try restarting it by unplugging for 30 seconds.',
  },
  mac_address: {
    title: 'MAC Address',
    what: 'A MAC (Media Access Control) address is a unique hardware identifier assigned to every network interface.',
    how: 'It\'s a 48-bit number usually written as XX:XX:XX:XX:XX:XX. The first 3 pairs identify the manufacturer.',
    why: 'MAC addresses help identify devices on your local network. They never leave your local network (unlike IP addresses).',
    tip: 'If you see an unfamiliar MAC address on your network, use the vendor lookup to identify who made the device.',
  },
  ip_address: {
    title: 'Local IP Address',
    what: 'Your local IP address is how devices communicate within your home network.',
    how: 'Assigned by your router via DHCP. Usually starts with 192.168.x.x or 10.x.x.x.',
    why: 'Local IPs are private — they\'re not visible on the internet. Your router uses NAT to translate them.',
    tip: 'If two devices have the same IP, you\'ll have connection conflicts. This is called an IP conflict.',
  },
  public_ip: {
    title: 'Public IP Address',
    what: 'Your public IP is the address your internet provider assigns to your home network — visible to the internet.',
    how: 'All devices on your home network share one public IP. Websites see this when you connect.',
    why: 'Your public IP can be used to roughly identify your location and ISP. It may change periodically.',
    tip: 'Use a VPN if you want to hide your public IP from websites you visit.',
  },
  subnet: {
    title: 'Subnet / Network Range',
    what: 'A subnet defines the range of IP addresses available on your local network.',
    how: 'Typically /24 (192.168.x.0/24) which allows 254 devices. The last number ranges from 1-254.',
    why: 'Understanding your subnet helps you discover and scan all devices on your network.',
    tip: 'Most home routers use 192.168.1.0/24 or 192.168.0.0/24 with up to 254 connected devices.',
  },
  port: {
    title: 'Network Port',
    what: 'A port is a numbered endpoint that identifies a specific service or application on a device.',
    how: 'Ports range from 0-65535. Common ones: 80 (HTTP), 443 (HTTPS), 22 (SSH), 21 (FTP).',
    why: 'Open ports are entry points into a device. Unnecessary open ports increase attack surface.',
    tip: 'Close any ports you don\'t need. Port 23 (Telnet) should always be closed — it sends data unencrypted.',
  },
  arp: {
    title: 'ARP (Address Resolution Protocol)',
    what: 'ARP maps IP addresses to MAC addresses on a local network.',
    how: 'When a device wants to communicate with an IP, it broadcasts "who has this IP?" and the owner responds.',
    why: 'ARP spoofing (poisoning) is when an attacker sends fake ARP replies to intercept your traffic.',
    tip: 'If your gateway\'s MAC address changes between scans, it could indicate ARP spoofing. Use a VPN if suspected.',
  },
  ssid: {
    title: 'SSID (Network Name)',
    what: 'The SSID is the name of your WiFi network — what you see when searching for networks to join.',
    how: 'Broadcast by your router in beacon frames every 102.4ms. Up to 32 characters long.',
    why: 'Hiding your SSID doesn\'t meaningfully improve security — devices still broadcast it when connecting.',
    tip: 'Use a unique SSID that doesn\'t reveal your location or router model (e.g., avoid "Netgear_Home_2024").',
  },
  channel: {
    title: 'WiFi Channel',
    what: 'WiFi channels are frequency sub-bands within the 2.4GHz or 5GHz spectrum used for wireless communication.',
    how: '2.4GHz has 14 channels (1-14) but only 1, 6, and 11 are non-overlapping. 5GHz has many more.',
    why: 'When many networks use the same channel, they interfere with each other, causing slower speeds.',
    tip: 'Use the Channel Analyzer to find the least congested channel and switch your router to it.',
  },
  frequency: {
    title: 'WiFi Frequency Band',
    what: 'WiFi operates on two main frequency bands: 2.4GHz and 5GHz.',
    how: '2.4GHz travels farther but is slower. 5GHz is faster but has shorter range and more interference.',
    why: 'Choosing the right band improves performance. 2.4GHz is better for far rooms; 5GHz for close, high-speed use.',
    tip: 'Most modern routers support both. Use 5GHz when close to the router, 2.4GHz for better range.',
  },
  ttl: {
    title: 'TTL (Time to Live)',
    what: 'TTL is a counter that limits how long a packet can circulate on the internet.',
    how: 'Each router a packet passes through decrements the TTL by 1. When it hits 0, the packet is dropped.',
    why: 'TTL prevents packets from circulating forever in routing loops. It also reveals the OS — Windows uses 128, Linux uses 64.',
    tip: 'A TTL of 64 often means a Linux/Android device. 128 suggests Windows. 255 may indicate a network device.',
  },
  download_speed: {
    title: 'Download Speed',
    what: 'Download speed measures how fast data travels from the internet to your device.',
    how: 'Measured in Mbps (megabits per second). 1 Mbps = 125 KB/s. 100 Mbps can download a HD movie in ~8 minutes.',
    why: 'Affects streaming quality, web page loads, file downloads, and app updates.',
    tip: 'Netflix HD needs 5 Mbps, 4K needs 25 Mbps. Video calls need at least 3 Mbps per participant.',
  },
  upload_speed: {
    title: 'Upload Speed',
    what: 'Upload speed measures how fast data travels from your device to the internet.',
    how: 'Usually much lower than download on residential connections. Measured in Mbps.',
    why: 'Affects video calls, file sharing, cloud backups, and streaming your own content.',
    tip: 'For stable video calls, you need at least 1.5 Mbps upload per active camera stream.',
  },
  security_type: {
    title: 'WiFi Security Type',
    what: 'The encryption protocol protecting data transmitted on your WiFi network.',
    how: 'WEP (2001, broken), WPA (2003, weak), WPA2 (2004, standard), WPA3 (2018, current best).',
    why: 'Weak security lets nearby attackers intercept all your network traffic including passwords.',
    tip: 'Upgrade to WPA3 if your router supports it. At minimum use WPA2. WEP networks are completely insecure.',
  },
  device_vendor: {
    title: 'Device Vendor / Manufacturer',
    what: 'The company that manufactured the network interface of a device, identified from the MAC address.',
    how: 'The first 3 bytes of every MAC address (OUI) are assigned to manufacturers by the IEEE.',
    why: 'Helps identify unknown devices on your network — you can see if it\'s Apple, Samsung, etc.',
    tip: 'An unrecognized vendor on your network could be an intruder. Check your router\'s connected devices list.',
  },
  health_score: {
    title: 'Network Health Score',
    what: 'A composite score (0-100) rating the overall health of your network connection.',
    how: 'Calculated from 5 sub-scores: signal strength, latency, security, device count, and stability.',
    why: 'Provides a quick at-a-glance understanding of your network quality without reading individual metrics.',
    tip: 'Focus on the sub-score with the lowest value first — that\'s your biggest bottleneck.',
  },
  stability_score: {
    title: 'Network Stability',
    what: 'Measures how consistent your connection is over time — how much your latency varies.',
    how: 'Based on jitter: the variance between ping readings. Low jitter = stable. High jitter = unstable.',
    why: 'An unstable connection causes worse experience than a consistently slower one for real-time apps.',
    tip: 'If stability is low, check for WiFi interference, try a wired connection, or restart your router.',
  },
  isp: {
    title: 'ISP (Internet Service Provider)',
    what: 'Your ISP is the company providing your internet connection.',
    how: 'Identified from your public IP address using IP geolocation databases.',
    why: 'Your ISP controls your upstream bandwidth, DNS defaults, and can see your unencrypted traffic.',
    tip: 'Use 1.1.1.1 or 8.8.8.8 as DNS to avoid ISP-level DNS filtering and improve privacy.',
  },
  asn: {
    title: 'ASN (Autonomous System Number)',
    what: 'An ASN is a unique identifier for a network operated by a single organization on the internet.',
    how: 'ISPs, universities, and large companies each have their own ASN. Used for internet routing.',
    why: 'Can help identify your ISP, detect VPN usage, or spot unexpected network routing.',
    tip: 'If your ASN changes unexpectedly, your traffic may be routing through a different network.',
  },
  tls_certificate: {
    title: 'TLS/SSL Certificate',
    what: 'A digital certificate that proves a website\'s identity and enables encrypted HTTPS connections.',
    how: 'Issued by Certificate Authorities (CAs). Contains the domain name, issuer, validity period, and public key.',
    why: 'Without a valid certificate, your connection to a website is not encrypted or verified.',
    tip: 'Check that certificates don\'t expire. An expired certificate leaves users with browser warnings.',
  },
  http_headers: {
    title: 'HTTP Response Headers',
    what: 'Metadata sent by a web server with every response, containing instructions for the browser.',
    how: 'Includes security headers (HSTS, CSP), content type, caching rules, and server information.',
    why: 'Missing security headers leave websites vulnerable to XSS, clickjacking, and MITM attacks.',
    tip: 'Check for HSTS, Content-Security-Policy, X-Frame-Options, and X-Content-Type-Options headers.',
  },
  traceroute: {
    title: 'Traceroute',
    what: 'Traceroute maps the path data takes from your device to a destination, showing each hop along the way.',
    how: 'Sends packets with increasing TTL values. Each router that drops a packet reveals its IP and latency.',
    why: 'Helps identify where bottlenecks, high latency, or failures occur in the network path.',
    tip: 'Hops with * * * are routers that block ICMP probes — not necessarily a problem.',
  },
  bandwidth: {
    title: 'Bandwidth',
    what: 'Bandwidth is the maximum rate of data transfer across a network path.',
    how: 'Measured in Mbps or Gbps. It\'s the "width of the pipe" — the maximum, not the current usage.',
    why: 'Insufficient bandwidth causes slowdowns when multiple devices or applications use the network simultaneously.',
    tip: 'Check your plan\'s bandwidth and compare with your speed test to see if you\'re getting what you pay for.',
  },
  ping_count: {
    title: 'Ping Count',
    what: 'The number of ping packets sent in a test sequence.',
    how: 'More pings give a more accurate picture of latency and jitter. Fewer pings are faster.',
    why: 'A single ping can be misleading. Multiple pings reveal the range and consistency of your connection.',
    tip: 'Use 10 pings for accurate measurements. Use 4 for quick checks. Use 1 only to verify connectivity.',
  },
  dns_server: {
    title: 'DNS Server',
    what: 'The server that resolves domain names to IP addresses for your network.',
    how: 'Usually set by your ISP via DHCP. Can be manually changed in network settings or router.',
    why: 'Your DNS server can see every domain you visit. ISP DNS is often slower and less private.',
    tip: 'Switch to 1.1.1.1 (Cloudflare) for the fastest, most private DNS. Or 9.9.9.9 (Quad9) for security-focused DNS.',
  },
  wol: {
    title: 'Wake-on-LAN (WoL)',
    what: 'Wake-on-LAN is a network standard that allows a device to be powered on remotely.',
    how: 'Sends a "magic packet" — 6 bytes of FF followed by the target MAC address repeated 16 times — to UDP port 9.',
    why: 'Lets you turn on computers remotely without having to physically press the power button.',
    tip: 'The target device must have WoL enabled in its BIOS/UEFI and network adapter settings.',
  },
  whois: {
    title: 'WHOIS Lookup',
    what: 'WHOIS is a protocol that provides registration information about domain names and IP addresses.',
    how: 'Queries public databases maintained by domain registrars and regional internet registries (RIRs).',
    why: 'Useful for finding the owner, registrar, creation date, and abuse contacts for a domain or IP.',
    tip: 'Many registrars offer WHOIS privacy protection that hides personal contact information.',
  },
};
